/** @format */

export default {
  SET_INSTANCE_DETAILS: "SET_INSTANCE_DETAILS",
  SET_REGION: "SET_REGION",
  SET_CONFIG: "SET_CONFIG",
  RESET: "RESET",
  SET_TEST: "SET_TEST",
  SET_SELECTION_TEST: "SET_SELECTION_TEST",
  SET_HELPPANEL: "SET_HELPPANEL",
};
